name: wolfsker_test
favicon: null
layout_spectrum: 0.49644786887802184
typography_spectrum: 0.8117660349234939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2885474832728505
  lightness: 0.7853970755822957
  saturation: 0.4229652874637395
  rhythmicContrast: 0.937352407258004
purpose: []
